### PR TITLE
Install DOI Search In DOI UI #106

### LINKED ISSUE #106: Update DOI UI app to use NPM package

### LINKED ISSUE #117: Fix DOI Search And DOI UI Integration Bugs
Fix these bugs that occur when the DOI Search is installed into the DOI UI.

- [ ] Hovering over status value will crash the app. A tooltip is supposed to show but something must be causing an error.
- [ ] Going to the search page will cause the app bar to become white and jumbled. There must be some sort of styling issue.

The tool tip is probably crashing because of a missing file reference.

It looks like the styling for material UI is being loaded twice. It might be be caused by conflicting material UI imports.

### PR DESCRIPTION
**Pull request by eddiesarevalo**
## 🗒️ Summary
DOI Search has been installed into the DOI UI.
Integration bugs have been addressed in the doi search, #117 and #106 

## ♻️ Related Issues
        - fixes #117
        - resolves #106

### CODE REVIEW

**Review by tloubrieu-jpl — CHANGES_REQUESTED** [review]
Hi @eddiesarevalo ,

Thanks for the pull request.

I did the checkout the branch, then npm install and npm start and I am seeing the error you had when hovering on the status.

See video here:
https://user-images.githubusercontent.com/60993872/156820560-6b842c38-2ceb-493d-93bd-60fced8b2917.mov

Do you understand what the issue can be ?

Thanks

Thomas

**Comment by eddiesarevalo** [comment]
Hello @tloubrieu-jpl, it looks like the package-lock.json is pointing to pds-wds-react version 0.0.1 which is the really broken version. It should be pointing to 0.0.2-beta.3

It looks like the versions are correct in the pds-wds-react package so the problem should be in the doi-ui.  I will try to update the package-lock.json in the doi-ui

**Comment by tloubrieu-jpl** [comment]
Thanks @eddiesarevalo , should the file package-lock.json be managed in git ?

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl Yes the package-lock.json file should be tracked by git. I have set the version of pds-wds-react to be used in the doi-ui to be `0.0.2-beta.3` I put an exact match as trying to to use the `~`(minor version) or `^`(major version) will ignore the beta version. 

Once the latest pds-wds-react is merged back to main then we can remove the exact version and use the latest pds-wds-react.

**Review by tloubrieu-jpl — APPROVED** [review]
package-lock.json is 1.6Mb. We would need to clarify if it is actually needed or need to be that big. It is a detail though

**Pull request merged**
